const fs = require('fs');
const file = 'C:\\Users\\tomav\\tradingview-mcp-jackson\\hank-electron-r2.html';

const s678 = `

<!-- ══════════════════ TAB 4: P&L DASHBOARD ════════════════ -->
<div class="tab-panel" id="tab-pnl">

  <!-- ACCOUNT STATS -->
  <div class="pnl-stats">
    <div class="pnl-sc">
      <div class="pnl-sc-lbl">BALANCE</div>
      <div class="pnl-sc-val pos" id="pnl-balance">$1,247.50</div>
    </div>
    <div class="pnl-sc">
      <div class="pnl-sc-lbl">TODAY P&amp;L</div>
      <div class="pnl-sc-val pos" id="pnl-today">+$247.50</div>
    </div>
    <div class="pnl-sc">
      <div class="pnl-sc-lbl">ALL-TIME P&amp;L</div>
      <div class="pnl-sc-val pos" id="pnl-alltime">+$247.50</div>
    </div>
    <div class="pnl-sc">
      <div class="pnl-sc-lbl">WIN RATE</div>
      <div class="pnl-sc-val neu" id="pnl-winrate">--</div>
    </div>
    <div class="pnl-sc">
      <div class="pnl-sc-lbl">PROFIT FACTOR</div>
      <div class="pnl-sc-val neu" id="pnl-pf">--</div>
    </div>
  </div>

  <!-- LEVELS CARDS -->
  <div style="display:grid;grid-template-columns:repeat(3,1fr);gap:6px;margin-bottom:10px;" id="pnl-levels">
    <div class="pnl-sc">
      <div style="color:var(--blue);font-size:16px;font-weight:bold;margin-bottom:5px;">SPY</div>
      <div style="font-size:22px;color:#fff;">714.01</div>
      <div style="font-size:12px;margin-top:5px;display:grid;grid-template-columns:1fr 1fr;gap:3px;">
        <span style="color:var(--red);">PDH 714.47</span>
        <span style="color:var(--green);">PDL 709.21</span>
        <span style="color:#777;">VWAP 711.99</span>
        <span style="color:var(--green);">BULL ✓</span>
      </div>
    </div>
    <div class="pnl-sc">
      <div style="color:var(--blue);font-size:16px;font-weight:bold;margin-bottom:5px;">QQQ</div>
      <div style="font-size:22px;color:#fff;">484.20</div>
      <div style="font-size:12px;margin-top:5px;display:grid;grid-template-columns:1fr 1fr;gap:3px;">
        <span style="color:var(--red);">PDH 486.10</span>
        <span style="color:var(--green);">PDL 481.33</span>
        <span style="color:#777;">VWAP 484.42</span>
        <span style="color:var(--yellow);">NEUTRAL</span>
      </div>
    </div>
    <div class="pnl-sc">
      <div style="color:var(--blue);font-size:16px;font-weight:bold;margin-bottom:5px;">IWM</div>
      <div style="font-size:22px;color:#fff;">198.44</div>
      <div style="font-size:12px;margin-top:5px;display:grid;grid-template-columns:1fr 1fr;gap:3px;">
        <span style="color:var(--red);">PDH 199.22</span>
        <span style="color:var(--green);">PDL 196.14</span>
        <span style="color:#777;">VWAP 197.56</span>
        <span style="color:var(--green);">BULL ✓</span>
      </div>
    </div>
  </div>

  <!-- OPEN POSITIONS -->
  <div class="pnl-tbl-wrap">
    <div class="pnl-tbl-title">OPEN POSITIONS</div>
    <table class="pnl-tbl">
      <thead>
        <tr><th>INSTRUMENT</th><th>DIRECTION</th><th>STRIKE</th><th>EXPIRY</th><th>ENGINE</th><th>ENTRY</th><th>EST CURRENT</th><th>P&amp;L $</th><th>P&amp;L %</th><th>HOLD</th><th>STATUS</th></tr>
      </thead>
      <tbody id="pnl-open-tbody">
        <tr><td colspan="11" class="no-data">No open positions</td></tr>
      </tbody>
    </table>
  </div>

  <!-- CLOSED TRADES -->
  <div class="pnl-tbl-wrap">
    <div class="pnl-tbl-title">TODAY'S CLOSED TRADES</div>
    <table class="pnl-tbl">
      <thead>
        <tr><th>INSTRUMENT</th><th>DIRECTION</th><th>ENGINE</th><th>ENTRY</th><th>EXIT</th><th>P&amp;L $</th><th>P&amp;L %</th><th>DURATION</th><th>RESULT</th></tr>
      </thead>
      <tbody id="pnl-closed-tbody">
        <tr><td colspan="9" class="no-data">No closed trades today</td></tr>
      </tbody>
    </table>
  </div>

  <!-- MOO/MOC SIGNALS -->
  <div class="pnl-sig-row">
    <div class="pnl-sig-card">
      <div class="pnl-sig-type">MOO — MARKET ON OPEN</div>
      <div class="pnl-sig-dir" style="color:var(--green);">+$2.4B BUY CALLS</div>
      <div class="pnl-sig-det">S&amp;P Net +$2.4B · MAG7 +$680M · Indices ALIGNED ✓<br>Threshold: $1B+ · Time: 09:25:02 ET</div>
      <div class="pnl-sig-meta">🟢 GREEN — TRADEABLE · B1 entered 09:35 · Signal generated by moc.js</div>
    </div>
    <div class="pnl-sig-card">
      <div class="pnl-sig-type">MOC — MARKET ON CLOSE</div>
      <div class="pnl-sig-dir pnl-sig-none">No MOC signal yet</div>
      <div class="pnl-sig-meta">MOC window opens 15:45 ET · waiting for imbalance data</div>
    </div>
  </div>

</div><!-- end tab-pnl -->

<!-- ══════════════════ TAB 5: TRADE ═════════════════════════ -->
<div class="tab-panel" id="tab-trade">
  <div class="trade-grid">

    <!-- TRADE COMMAND -->
    <div class="trade-cmd">
      <div class="tc2-logo">⬡ TRADE COMMAND</div>
      <div class="tc2-sub">UNIVERSAL OPTIONS EXECUTOR</div>

      <!-- SIGNAL BANNER -->
      <div class="sig-banner">
        <div style="display:flex;align-items:center;gap:10px;">
          <span class="sb-badge sb-calls" id="trade-sig-badge">TAKE CALLS</span>
          <div>
            <div style="color:#ccc;font-size:12px;" id="trade-sig-text">SPY — TAKE CALLS</div>
            <div style="color:var(--mid);font-size:10px;" id="trade-sig-conf">HIGH · 4/6 BULL + SPY bullish + $TICK +642 + MOO $2.4B</div>
          </div>
        </div>
        <button class="sb-load" onclick="loadHankSignal()">⬡ LOAD</button>
      </div>

      <!-- MODE -->
      <div class="mode-row">
        <button class="mode-btn2 mode-calls active" id="mode-calls-btn" onclick="setTradeSide('calls')">▲ CALLS</button>
        <button class="mode-btn2 mode-puts" id="mode-puts-btn" onclick="setTradeSide('puts')">▼ PUTS</button>
        <button class="mode-btn2 mode-paper active" id="mode-paper-btn" onclick="setTradeMode('paper')">◈ PAPER</button>
        <button class="mode-btn2 mode-paper" id="mode-live-btn" onclick="setTradeMode('live')" style="border-color:rgba(255,68,68,0.3);color:rgba(255,68,68,0.4);">● LIVE</button>
      </div>

      <!-- QUICK SYMBOLS -->
      <div style="font-size:10px;color:var(--mid);letter-spacing:2px;margin-bottom:5px;">QUICK SELECT</div>
      <div class="quick-row" id="quickRow"></div>

      <!-- SYMBOL INPUT -->
      <div style="font-size:10px;color:var(--mid);letter-spacing:2px;margin-bottom:5px;">SYMBOL</div>
      <div class="sym-row" style="margin-bottom:6px;">
        <input class="sym-input" id="symInput" type="text" placeholder="SPY, IWM, HOOD..." maxlength="8" autocomplete="off">
        <button class="sym-fetch" onclick="fetchSymbol()">FETCH ▸</button>
      </div>

      <!-- QUOTE STRIP -->
      <div class="quote-strip" id="quoteStrip">
        <div class="qs-item"><div class="qs-lbl">PRICE</div><div class="qs-price" id="qsPrice">---</div></div>
        <span style="color:#1a1a2a;">│</span>
        <div class="qs-item"><div class="qs-lbl">CHANGE</div><div class="qs-val" id="qsChange">---</div></div>
        <span style="color:#1a1a2a;">│</span>
        <div class="qs-item"><div class="qs-lbl">VOLUME</div><div class="qs-val" id="qsVol">---</div></div>
        <span style="color:#1a1a2a;">│</span>
        <div class="qs-item"><div class="qs-lbl">IV RANK</div><div class="qs-val" id="qsIV">---</div></div>
        <span style="color:#1a1a2a;">│</span>
        <div class="qs-item"><div class="qs-lbl">BIAS</div><div class="qs-val" id="qsBias">---</div></div>
      </div>

      <!-- OPTIONS -->
      <div class="tc2-field-row">
        <div class="tc2-field">
          <label>EXPIRY</label>
          <select class="tc2-select" id="expirySelect" onchange="updateOrder()">
            <option value="0DTE">0DTE</option>
            <option value="1DTE">1DTE</option>
            <option value="WEEKLY">WEEKLY</option>
            <option value="MONTHLY">MONTHLY</option>
          </select>
        </div>
        <div class="tc2-field">
          <label>STRIKE TYPE</label>
          <select class="tc2-select" id="strikeType" onchange="calcStrike()">
            <option value="ATM">ATM</option>
            <option value="1OTM">1 OTM</option>
            <option value="2OTM">2 OTM</option>
            <option value="1ITM">1 ITM</option>
          </select>
        </div>
        <div class="tc2-field">
          <label>ORDER TYPE</label>
          <select class="tc2-select" id="orderType" onchange="updateOrder()">
            <option value="MKT">MARKET</option>
            <option value="LMT">LIMIT</option>
          </select>
        </div>
      </div>

      <!-- STRIKE DISPLAY -->
      <div class="tc2-field">
        <label>STRIKE PRICE</label>
        <div class="strike-display">
          <div>
            <div style="font-size:9px;color:var(--mid);letter-spacing:1px;margin-bottom:3px;" id="strikeLabel">ATM STRIKE</div>
            <div class="strike-val" id="strikeVal">---</div>
          </div>
          <div style="display:flex;gap:3px;">
            <button class="adj-btn" onclick="adjustStrike(-1)">−</button>
            <button class="adj-btn" onclick="adjustStrike(+1)">+</button>
          </div>
        </div>
      </div>

      <!-- SIZING -->
      <div style="font-size:10px;color:var(--mid);letter-spacing:2px;margin-bottom:5px;">CONTRACT SIZE</div>
      <div class="size-grid">
        <div class="size-opt active" id="size1" onclick="setSize(1)">
          <div class="size-opt-num">1</div><div>CONTRACT</div>
        </div>
        <div class="size-opt" id="size2" onclick="setSize(2)">
          <div class="size-opt-num">2</div><div>CONTRACTS</div>
        </div>
        <div class="size-opt" id="size3" onclick="setSize(3)">
          <div class="size-opt-num">3</div><div>CONTRACTS</div>
        </div>
        <div class="size-opt" id="sizeA" onclick="setSize('auto')">
          <div class="size-opt-num">AUTO</div><div>BY BALANCE</div>
        </div>
      </div>

      <!-- ORDER PREVIEW -->
      <div style="font-size:10px;color:var(--mid);letter-spacing:2px;margin-bottom:5px;">ORDER PREVIEW</div>
      <div class="order-preview">
        <div class="order-line" id="orderLine">Select symbol and direction</div>
        <div class="order-meta" id="orderMeta"></div>
      </div>

      <!-- EXECUTE -->
      <div class="exec-row">
        <button class="exec-btn exec-live" id="execLive" onclick="confirmOrder('live')" disabled>● EXECUTE LIVE</button>
        <button class="exec-btn exec-paper" onclick="confirmOrder('paper')">◈ PAPER TRADE</button>
      </div>
      <button class="close-all" onclick="closeAll()">✕ CLOSE ALL POSITIONS</button>
      <div style="text-align:center;margin-top:6px;font-size:10px;color:var(--yellow);letter-spacing:1px;padding:4px;background:rgba(255,170,0,0.04);border:1px solid rgba(255,170,0,0.15);" id="modeNote">◈ PAPER MODE — no real money at risk</div>

      <!-- TRADE LOG -->
      <div class="trade-log-wrap" style="margin-top:12px;">
        <div class="tl-hdr">TRADE LOG — TODAY</div>
        <div class="tl-hdr-row">
          <span>TIME</span><span>SYM</span><span>TYPE</span><span>ORDER</span><span>ENTRY</span><span>STATUS</span>
        </div>
        <div class="tl-body" id="logBody">
          <div class="tl-empty">No trades today.</div>
        </div>
      </div>
    </div>

    <!-- POSITIONS PANEL -->
    <div class="pos-panel">
      <div class="pos-ph">
        <span class="pos-ptitle">OPEN POSITIONS</span>
        <span class="pos-cnt" id="posCountBadge">0 positions</span>
      </div>
      <div class="pos-body" id="posBody">
        <div class="pos-empty">
          No open positions.<br>
          Execute a trade to open a position.<br>
          <span style="color:#1a1a2a;">Paper + live tracking here.</span>
        </div>
      </div>
    </div>

  </div>
</div><!-- end tab-trade -->

<!-- ══════════════════ TAB 6: SETTINGS ══════════════════════ -->
<div class="tab-panel" id="tab-settings">

  <!-- LAUNCH TV BUTTON — prominent at top -->
  <div style="padding:20px 20px 0;">
    <button class="launch-tv-btn" onclick="launchTradingView()">
      ◈ LAUNCH TRADINGVIEW — CONNECT CDP :9222
    </button>
    <div style="text-align:center;font-size:11px;color:#333;margin-top:8px;letter-spacing:1px;">
      Opens TradingView Desktop with Chrome DevTools Protocol enabled for HANK AI control
    </div>
  </div>

  <div style="padding:16px 20px;">
  <div class="settings-grid">

    <div class="sc">
      <div class="sc-title">TRADING MODE</div>
      <div class="sc-body">
        <div class="setting-row">
          <div><div class="sr-label">Execution Mode</div><div class="sr-sub">Paper = simulated · Live = real money via Webull API</div></div>
          <div class="toggle-g">
            <button class="tgl-btn active paper" onclick="setSettingMode('paper',this)">PAPER</button>
            <button class="tgl-btn live" onclick="setSettingMode('live',this)">LIVE</button>
          </div>
        </div>
        <div class="setting-row">
          <div><div class="sr-label">Auto-Trade Engine</div><div class="sr-sub">Execute signals without manual confirmation</div></div>
          <div class="toggle-g">
            <button class="tgl-btn active off" onclick="setToggle('auto',this,'on')">OFF</button>
            <button class="tgl-btn on" onclick="setToggle('auto',this,'off')">ON</button>
          </div>
        </div>
        <div class="setting-row">
          <div><div class="sr-label">Confidence Threshold</div><div class="sr-sub">Minimum signal confidence for auto-execution</div></div>
          <select style="background:var(--bg3);border:1px solid #1a1a2a;color:#ccc;padding:4px 8px;font-family:var(--mono);font-size:10px;outline:none;">
            <option>HIGH only</option>
            <option>MEDIUM+</option>
            <option>SPY+W3 override</option>
          </select>
        </div>
        <div class="setting-row">
          <div><div class="sr-label">Max Risk Per Trade</div></div>
          <input type="number" value="100" style="background:var(--bg3);border:1px solid #1a1a2a;color:#fff;padding:4px 8px;font-family:var(--mono);font-size:11px;width:80px;outline:none;text-align:right;">
        </div>
      </div>
    </div>

    <div class="sc">
      <div class="sc-title">API CONNECTIONS</div>
      <div class="sc-body">
        <div class="setting-row">
          <div><div class="sr-label">TradingView CDP</div><div class="sr-sub">localhost:9222 Chrome DevTools</div></div>
          <div class="api-status">
            <div class="api-dot api-ok" id="cdp-dot"></div>
            <span class="api-lbl" id="cdp-lbl">Connected</span>
          </div>
        </div>
        <div class="setting-row">
          <div><div class="sr-label">Webull API</div><div class="sr-sub">Paper trading / live orders</div></div>
          <div class="api-status">
            <div class="api-dot api-bad" id="wb-dot"></div>
            <span class="api-lbl" id="wb-lbl">Auth pending</span>
            <button class="sa-btn" onclick="reAuthWebull()" style="margin-left:6px;">RE-AUTH</button>
          </div>
        </div>
        <div class="setting-row">
          <div><div class="sr-label">Polygon.io</div><div class="sr-sub">Options data · earnings · IV rank</div></div>
          <div class="api-status">
            <div class="api-dot api-ok"></div>
            <span class="api-lbl">Connected</span>
          </div>
        </div>
        <div class="setting-row">
          <div><div class="sr-label">Financial Juice / Reuters</div><div class="sr-sub">News feed · 30s poll</div></div>
          <div class="api-status">
            <div class="api-dot api-ok"></div>
            <span class="api-lbl">Live</span>
          </div>
        </div>
      </div>
    </div>

    <div class="sc">
      <div class="sc-title">SERVICES CONTROL</div>
      <div class="sc-body">
        <div class="setting-row">
          <div><div class="sr-label">monitor.js</div><div class="sr-sub">Market monitor · 30s SPY poll · signals</div></div>
          <div class="toggle-g">
            <button class="tgl-btn active on">RUNNING</button>
            <button class="tgl-btn off" onclick="svcToggle('monitor')">STOP</button>
          </div>
        </div>
        <div class="setting-row">
          <div><div class="sr-label">news.js</div><div class="sr-sub">News aggregator · FJ · Reuters · SEC</div></div>
          <div class="toggle-g">
            <button class="tgl-btn active on">RUNNING</button>
            <button class="tgl-btn off" onclick="svcToggle('news')">STOP</button>
          </div>
        </div>
        <div class="setting-row">
          <div><div class="sr-label">moc.js</div><div class="sr-sub">MOC/MOO imbalance signals</div></div>
          <div class="toggle-g">
            <button class="tgl-btn off active">STOPPED</button>
            <button class="tgl-btn on" onclick="svcToggle('moc')">START</button>
          </div>
        </div>
        <div class="setting-row">
          <div><div class="sr-label">mailer.js</div><div class="sr-sub">Email briefings · alert notifications</div></div>
          <div class="toggle-g">
            <button class="tgl-btn off active">STOPPED</button>
            <button class="tgl-btn on" onclick="svcToggle('mailer')">START</button>
          </div>
        </div>
      </div>
    </div>

    <div class="sc">
      <div class="sc-title">RISK MANAGEMENT</div>
      <div class="sc-body">
        <div class="setting-row">
          <div><div class="sr-label">Death Zone Block</div><div class="sr-sub">No trades 11:50–14:30 ET</div></div>
          <div class="toggle-g">
            <button class="tgl-btn active on">ON</button>
            <button class="tgl-btn off" onclick="setToggle('dz',this,'off')">OFF</button>
          </div>
        </div>
        <div class="setting-row">
          <div><div class="sr-label">Two-Strike System</div><div class="sr-sub">Auto-halt after 2 losing auto-trades</div></div>
          <div class="toggle-g">
            <button class="tgl-btn active on">ON</button>
            <button class="tgl-btn off">OFF</button>
          </div>
        </div>
        <div class="setting-row">
          <div><div class="sr-label">TTS Announcements</div><div class="sr-sub">Speak signals, news, fill confirmations</div></div>
          <div class="toggle-g">
            <button class="tgl-btn active on">ON</button>
            <button class="tgl-btn off">OFF</button>
          </div>
        </div>
        <div class="setting-row">
          <div><div class="sr-label">Daily Loss Limit</div></div>
          <div style="display:flex;align-items:center;gap:6px;">
            <span style="color:var(--mid);font-size:11px;">$</span>
            <input type="number" value="200" style="background:var(--bg3);border:1px solid #1a1a2a;color:#fff;padding:4px 8px;font-family:var(--mono);font-size:11px;width:70px;outline:none;text-align:right;">
            <span style="color:var(--dim);font-size:10px;">halt on hit</span>
          </div>
        </div>
      </div>
    </div>

  </div>
  </div><!-- end settings padding -->
</div><!-- end tab-settings -->

</div><!-- end content -->
</div><!-- end main-area -->
</div><!-- end shell -->`;

fs.appendFileSync(file, s678);
console.log('S678 done:', s678.length);
